version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: frontend.dockerfile
        container_name: frontend
        ports:
            - 3000:3000
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - frontend
        ports:
            - 80:80
        volumes:
            - /var/jenkins_home/workspace/ecommerce_main@tmp/nginx.conf:/etc/nginx/nginx.conf:ro
    backend:
        build:
            context: ./backend
            dockerfile: backend.dockerfile
        container_name: backend
        ports:
            - 8080:8080
